In [32]:
import os
import shutil

import pandas as pd
import numpy as np
import json

In [33]:
df=pd.DataFrame(columns=['jd','resume','macro_scores','micro_scores'])

In [34]:
df

Empty DataFrame
Columns: [jd, resume, macro_scores, micro_scores]
Index: []

In [35]:
data_to_load=[x for x in os.listdir("resume-score-details") if (x.split(".")[-1]=="json" and x.split("_")[0]!="invalid")]
data_to_load

['empty_additional_info_0.json',
 'empty_additional_info_1.json',
 'empty_additional_info_10.json',
 'empty_additional_info_11.json',
 'empty_additional_info_110.json',
 'empty_additional_info_111.json',
 'empty_additional_info_112.json',
 'empty_additional_info_113.json',
 'empty_additional_info_114.json',
 'empty_additional_info_115.json',
 'empty_additional_info_116.json',
 'empty_additional_info_117.json',
 'empty_additional_info_118.json',
 'empty_additional_info_119.json',
 'empty_additional_info_12.json',
 'empty_additional_info_120.json',
 'empty_additional_info_121.json',
 'empty_additional_info_122.json',
 'empty_additional_info_123.json',
 'empty_additional_info_124.json',
 'empty_additional_info_125.json',
 'empty_additional_info_13.json',
 'empty_additional_info_14.json',
 'empty_additional_info_15.json',
 'empty_additional_info_16.json',
 'empty_additional_info_17.json',
 'empty_additional_info_18.json',
 'empty_additional_info_19.json',
 'empty_additional_info_2.json',
 'empty_additional_info_20.json',
 'empty_additional_info_21.json',
 'empty_additional_info_22.json',
 'empty_additional_info_23.json',
 'empty_additional_info_3.json',
 'empty_additional_info_4.json',
 'empty_additional_info_5.json',
 'empty_additional_info_6.json',
 'empty_additional_info_7.json',
 'empty_additional_info_8.json',
 'empty_additional_info_9.json',
 'match_0.json',
 'match_1.json',
 'match_10.json',
 'match_100.json',
 'match_101.json',
 'match_102.json',
 'match_103.json',
 'match_104.json',
 'match_105.json',
 'match_106.json',
 'match_107.json',
 'match_108.json',
 'match_109.json',
 'match_11.json',
 'match_110.json',
 'match_111.json',
 'match_112.json',
 'match_113.json',
 'match_114.json',
 'match_115.json',
 'match_116.json',
 'match_117.json',
 'match_118.json',
 'match_119.json',
 'match_12.json',
 'match_120.json',
 'match_121.json',
 'match_122.json',
 'match_123.json',
 'match_124.json',
 'match_125.json',
 'match_126.json',
 'match_127.json',
 'match_128.json',
 'match_129.json',
 'match_13.json',
 'match_130.json',
 'match_131.json',
 'match_132.json',
 'match_133.json',
 'match_134.json',
 'match_135.json',
 'match_136.json',
 'match_137.json',
 'match_138.json',
 'match_139.json',
 'match_14.json',
 'match_140.json',
 'match_141.json',
 'match_142.json',
 'match_143.json',
 'match_144.json',
 'match_145.json',
 'match_146.json',
 'match_147.json',
 'match_148.json',
 'match_149.json',
 'match_15.json',
 'match_150.json',
 'match_151.json',
 'match_152.json',
 'match_153.json',
 'match_154.json',
 'match_155.json',
 'match_156.json',
 'match_157.json',
 'match_158.json',
 'match_159.json',
 'match_16.json',
 'match_160.json',
 'match_161.json',
 'match_162.json',
 'match_163.json',
 'match_164.json',
 'match_165.json',
 'match_166.json',
 'match_167.json',
 'match_168.json',
 'match_169.json',
 'match_17.json',
 'match_170.json',
 'match_171.json',
 'match_172.json',
 'match_173.json',
 'match_174.json',
 'match_175.json',
 'match_176.json',
 'match_177.json',
 'match_178.json',
 'match_179.json',
 'match_18.json',
 'match_180.json',
 'match_181.json',
 'match_182.json',
 'match_183.json',
 'match_184.json',
 'match_185.json',
 'match_186.json',
 'match_187.json',
 'match_188.json',
 'match_189.json',
 'match_19.json',
 'match_190.json',
 'match_191.json',
 'match_192.json',
 'match_193.json',
 'match_194.json',
 'match_195.json',
 'match_196.json',
 'match_197.json',
 'match_198.json',
 'match_199.json',
 'match_2.json',
 'match_20.json',
 'match_200.json',
 'match_201.json',
 'match_202.json',
 'match_203.json',
 'match_204.json',
 'match_205.json',
 'match_206.json',
 'match_207.json',
 'match_208.json',
 'match_209.json',
 'match_21.json',
 'match_210.json',
 'match_211.json',
 'match_212.json',
 'match_213.json',
 'match_214.json',
 'match_215.json',
 'match_216.json',
 'match_217.json',
 'match_218.json',
 'match_219.json',
 'match_22.json',
 'match_220.json',
 'match_221.json',
 'match_222.json',
 'match_223.json',
 'match_224.json',
 'match_225.json',
 'match_226.json',
 'match_227.json',
 'match_228.json',
 'match_229.json',
 'match_23.json',
 'match_230.json',
 'match_231.json',
 'match_232.json',
 'match_233.json',
 'match_234.json',
 'match_235.json',
 'match_236.json',
 'match_237.json',
 'match_238.json',
 'match_239.json',
 'match_24.json',
 'match_240.json',
 'match_241.json',
 'match_242.json',
 'match_243.json',
 'match_244.json',
 'match_245.json',
 'match_246.json',
 'match_247.json',
 'match_248.json',
 'match_249.json',
 'match_25.json',
 'match_250.json',
 'match_251.json',
 'match_252.json',
 'match_253.json',
 'match_254.json',
 'match_255.json',
 'match_256.json',
 'match_257.json',
 'match_258.json',
 'match_259.json',
 'match_26.json',
 'match_260.json',
 'match_261.json',
 'match_262.json',
 'match_263.json',
 'match_264.json',
 'match_265.json',
 'match_266.json',
 'match_267.json',
 'match_268.json',
 'match_269.json',
 'match_27.json',
 'match_270.json',
 'match_271.json',
 'match_272.json',
 'match_273.json',
 'match_274.json',
 'match_275.json',
 'match_276.json',
 'match_277.json',
 'match_278.json',
 'match_279.json',
 'match_28.json',
 'match_280.json',
 'match_281.json',
 'match_282.json',
 'match_283.json',
 'match_284.json',
 'match_285.json',
 'match_286.json',
 'match_287.json',
 'match_288.json',
 'match_289.json',
 'match_29.json',
 'match_290.json',
 'match_291.json',
 'match_292.json',
 'match_293.json',
 'match_294.json',
 'match_295.json',
 'match_296.json',
 'match_297.json',
 'match_298.json',
 'match_299.json',
 'match_3.json',
 'match_30.json',
 'match_300.json',
 'match_301.json',
 'match_302.json',
 'match_303.json',
 'match_304.json',
 'match_305.json',
 'match_306.json',
 'match_307.json',
 'match_308.json',
 'match_309.json',
 'match_31.json',
 'match_310.json',
 'match_311.json',
 'match_312.json',
 'match_313.json',
 'match_314.json',
 'match_315.json',
 'match_316.json',
 'match_317.json',
 'match_318.json',
 'match_319.json',
 'match_32.json',
 'match_320.json',
 'match_321.json',
 'match_322.json',
 'match_323.json',
 'match_324.json',
 'match_325.json',
 'match_326.json',
 'match_327.json',
 'match_328.json',
 'match_329.json',
 'match_33.json',
 'match_330.json',
 'match_331.json',
 'match_332.json',
 'match_333.json',
 'match_334.json',
 'match_335.json',
 'match_336.json',
 'match_337.json',
 'match_338.json',
 'match_339.json',
 'match_34.json',
 'match_340.json',
 'match_341.json',
 'match_342.json',
 'match_343.json',
 'match_344.json',
 'match_345.json',
 'match_346.json',
 'match_347.json',
 'match_348.json',
 'match_349.json',
 'match_35.json',
 'match_350.json',
 'match_351.json',
 'match_352.json',
 'match_353.json',
 'match_354.json',
 'match_355.json',
 'match_356.json',
 'match_357.json',
 'match_358.json',
 'match_359.json',
 'match_36.json',
 'match_360.json',
 'match_361.json',
 'match_362.json',
 'match_363.json',
 'match_364.json',
 'match_365.json',
 'match_366.json',
 'match_367.json',
 'match_368.json',
 'match_369.json',
 'match_37.json',
 'match_370.json',
 'match_371.json',
 'match_372.json',
 'match_373.json',
 'match_374.json',
 'match_375.json',
 'match_376.json',
 'match_377.json',
 'match_378.json',
 'match_379.json',
 'match_38.json',
 'match_380.json',
 'match_381.json',
 'match_382.json',
 'match_383.json',
 'match_384.json',
 'match_385.json',
 'match_386.json',
 'match_387.json',
 'match_388.json',
 'match_389.json',
 'match_39.json',
 'match_390.json',
 'match_391.json',
 'match_392.json',
 'match_393.json',
 'match_394.json',
 'match_395.json',
 'match_396.json',
 'match_397.json',
 'match_398.json',
 'match_399.json',
 'match_4.json',
 'match_40.json',
 'match_400.json',
 'match_401.json',
 'match_402.json',
 'match_403.json',
 'match_404.json',
 'match_405.json',
 'match_406.json',
 'match_407.json',
 'match_408.json',
 'match_409.json',
 'match_41.json',
 'match_410.json',
 'match_411.json',
 'match_412.json',
 'match_413.json',
 'match_414.json',
 'match_415.json',
 'match_416.json',
 'match_417.json',
 'match_418.json',
 'match_419.json',
 'match_42.json',
 'match_420.json',
 'match_421.json',
 'match_422.json',
 'match_423.json',
 'match_424.json',
 'match_425.json',
 'match_426.json',
 'match_427.json',
 'match_428.json',
 'match_429.json',
 'match_43.json',
 'match_430.json',
 'match_431.json',
 'match_432.json',
 'match_433.json',
 'match_434.json',
 'match_435.json',
 'match_436.json',
 'match_437.json',
 'match_438.json',
 'match_439.json',
 'match_44.json',
 'match_440.json',
 'match_441.json',
 'match_442.json',
 'match_443.json',
 'match_444.json',
 'match_445.json',
 'match_446.json',
 'match_447.json',
 'match_448.json',
 'match_449.json',
 'match_45.json',
 'match_450.json',
 'match_451.json',
 'match_452.json',
 'match_453.json',
 'match_454.json',
 'match_455.json',
 'match_456.json',
 'match_457.json',
 'match_458.json',
 'match_459.json',
 'match_46.json',
 'match_460.json',
 'match_461.json',
 'match_462.json',
 'match_463.json',
 'match_464.json',
 'match_465.json',
 'match_466.json',
 'match_467.json',
 'match_468.json',
 'match_469.json',
 'match_47.json',
 'match_470.json',
 'match_471.json',
 'match_472.json',
 'match_473.json',
 'match_474.json',
 'match_475.json',
 'match_476.json',
 'match_477.json',
 'match_478.json',
 'match_479.json',
 'match_48.json',
 'match_480.json',
 'match_481.json',
 'match_482.json',
 'match_483.json',
 'match_484.json',
 'match_485.json',
 'match_486.json',
 'match_487.json',
 'match_488.json',
 'match_489.json',
 'match_49.json',
 'match_490.json',
 'match_491.json',
 'match_492.json',
 'match_493.json',
 'match_494.json',
 'match_495.json',
 'match_496.json',
 'match_497.json',
 'match_498.json',
 'match_499.json',
 'match_5.json',
 'match_50.json',
 'match_500.json',
 'match_501.json',
 'match_502.json',
 'match_503.json',
 'match_504.json',
 'match_505.json',
 'match_506.json',
 'match_507.json',
 'match_508.json',
 'match_509.json',
 'match_51.json',
 'match_510.json',
 'match_511.json',
 'match_512.json',
 'match_513.json',
 'match_514.json',
 'match_515.json',
 'match_516.json',
 'match_517.json',
 'match_518.json',
 'match_519.json',
 'match_52.json',
 'match_520.json',
 'match_521.json',
 'match_522.json',
 'match_523.json',
 'match_524.json',
 'match_525.json',
 'match_526.json',
 'match_527.json',
 'match_528.json',
 'match_529.json',
 'match_53.json',
 'match_530.json',
 'match_531.json',
 'match_532.json',
 'match_533.json',
 'match_534.json',
 'match_535.json',
 'match_536.json',
 'match_537.json',
 'match_538.json',
 'match_539.json',
 'match_54.json',
 'match_540.json',
 'match_541.json',
 'match_542.json',
 'match_543.json',
 'match_544.json',
 'match_545.json',
 'match_546.json',
 'match_547.json',
 'match_548.json',
 'match_549.json',
 'match_55.json',
 'match_550.json',
 'match_551.json',
 'match_552.json',
 'match_553.json',
 'match_554.json',
 'match_555.json',
 'match_556.json',
 'match_557.json',
 'match_558.json',
 'match_559.json',
 'match_56.json',
 'match_560.json',
 'match_561.json',
 'match_562.json',
 'match_563.json',
 'match_564.json',
 'match_565.json',
 'match_566.json',
 'match_567.json',
 'match_568.json',
 'match_569.json',
 'match_57.json',
 'match_570.json',
 'match_571.json',
 'match_572.json',
 'match_573.json',
 'match_574.json',
 'match_575.json',
 'match_576.json',
 'match_577.json',
 'match_578.json',
 'match_579.json',
 'match_58.json',
 'match_580.json',
 'match_581.json',
 'match_582.json',
 'match_583.json',
 'match_584.json',
 'match_585.json',
 'match_586.json',
 'match_587.json',
 'match_588.json',
 'match_589.json',
 'match_59.json',
 'match_590.json',
 'match_591.json',
 'match_592.json',
 'match_593.json',
 'match_594.json',
 'match_595.json',
 'match_596.json',
 'match_597.json',
 'match_598.json',
 'match_599.json',
 'match_6.json',
 'match_60.json',
 'match_600.json',
 'match_601.json',
 'match_602.json',
 'match_603.json',
 'match_604.json',
 'match_605.json',
 'match_606.json',
 'match_607.json',
 'match_608.json',
 'match_609.json',
 'match_61.json',
 'match_610.json',
 'match_611.json',
 'match_612.json',
 'match_613.json',
 'match_614.json',
 'match_615.json',
 'match_616.json',
 'match_617.json',
 'match_618.json',
 'match_619.json',
 'match_62.json',
 'match_620.json',
 'match_621.json',
 'match_622.json',
 'match_623.json',
 'match_624.json',
 'match_625.json',
 'match_626.json',
 'match_627.json',
 'match_628.json',
 'match_629.json',
 'match_63.json',
 'match_630.json',
 'match_631.json',
 'match_632.json',
 'match_633.json',
 'match_634.json',
 'match_635.json',
 'match_636.json',
 'match_637.json',
 'match_638.json',
 'match_639.json',
 'match_64.json',
 'match_640.json',
 'match_641.json',
 'match_642.json',
 'match_643.json',
 'match_644.json',
 'match_645.json',
 'match_646.json',
 'match_647.json',
 'match_65.json',
 'match_66.json',
 'match_67.json',
 'match_68.json',
 'match_69.json',
 'match_7.json',
 'match_70.json',
 'match_71.json',
 'match_72.json',
 'match_73.json',
 'match_74.json',
 'match_75.json',
 'match_76.json',
 'match_77.json',
 'match_78.json',
 'match_79.json',
 'match_8.json',
 'match_80.json',
 'match_81.json',
 'match_82.json',
 'match_83.json',
 'match_84.json',
 'match_85.json',
 'match_86.json',
 'match_87.json',
 'match_88.json',
 'match_89.json',
 'match_9.json',
 'match_90.json',
 'match_91.json',
 'match_92.json',
 'match_93.json',
 'match_94.json',
 'match_95.json',
 'match_96.json',
 'match_97.json',
 'match_98.json',
 'match_99.json',
 'mismatch_0.json',
 'mismatch_1.json',
 'mismatch_10.json',
 'mismatch_100.json',
 'mismatch_101.json',
 'mismatch_102.json',
 'mismatch_103.json',
 'mismatch_104.json',
 'mismatch_105.json',
 'mismatch_106.json',
 'mismatch_107.json',
 'mismatch_108.json',
 'mismatch_109.json',
 'mismatch_11.json',
 'mismatch_110.json',
 'mismatch_111.json',
 'mismatch_112.json',
 'mismatch_113.json',
 'mismatch_114.json',
 'mismatch_115.json',
 'mismatch_116.json',
 'mismatch_117.json',
 'mismatch_118.json',
 'mismatch_119.json',
 'mismatch_12.json',
 'mismatch_120.json',
 'mismatch_121.json',
 'mismatch_122.json',
 'mismatch_123.json',
 'mismatch_124.json',
 'mismatch_125.json',
 'mismatch_126.json',
 'mismatch_127.json',
 'mismatch_128.json',
 'mismatch_129.json',
 'mismatch_13.json',
 'mismatch_130.json',
 'mismatch_131.json',
 'mismatch_132.json',
 'mismatch_133.json',
 'mismatch_134.json',
 'mismatch_135.json',
 'mismatch_136.json',
 'mismatch_137.json',
 'mismatch_138.json',
 'mismatch_139.json',
 'mismatch_14.json',
 'mismatch_140.json',
 'mismatch_141.json',
 'mismatch_142.json',
 'mismatch_143.json',
 'mismatch_144.json',
 'mismatch_145.json',
 'mismatch_146.json',
 'mismatch_147.json',
 'mismatch_148.json',
 'mismatch_149.json',
 'mismatch_15.json',
 'mismatch_150.json',
 'mismatch_151.json',
 'mismatch_152.json',
 'mismatch_153.json',
 'mismatch_154.json',
 'mismatch_155.json',
 'mismatch_156.json',
 'mismatch_157.json',
 'mismatch_158.json',
 'mismatch_159.json',
 'mismatch_16.json',
 'mismatch_160.json',
 'mismatch_161.json',
 'mismatch_162.json',
 'mismatch_163.json',
 'mismatch_164.json',
 'mismatch_165.json',
 'mismatch_166.json',
 'mismatch_167.json',
 'mismatch_168.json',
 'mismatch_169.json',
 'mismatch_17.json',
 'mismatch_170.json',
 'mismatch_171.json',
 'mismatch_172.json',
 'mismatch_173.json',
 'mismatch_174.json',
 'mismatch_175.json',
 'mismatch_176.json',
 'mismatch_177.json',
 'mismatch_178.json',
 'mismatch_179.json',
 'mismatch_18.json',
 'mismatch_180.json',
 'mismatch_181.json',
 'mismatch_182.json',
 'mismatch_183.json',
 'mismatch_184.json',
 'mismatch_185.json',
 'mismatch_186.json',
 'mismatch_187.json',
 'mismatch_188.json',
 'mismatch_189.json',
 'mismatch_19.json',
 'mismatch_190.json',
 'mismatch_191.json',
 'mismatch_192.json',
 'mismatch_193.json',
 'mismatch_194.json',
 'mismatch_195.json',
 'mismatch_196.json',
 'mismatch_197.json',
 'mismatch_198.json',
 'mismatch_199.json',
 'mismatch_2.json',
 'mismatch_20.json',
 'mismatch_200.json',
 'mismatch_21.json',
 'mismatch_22.json',
 'mismatch_23.json',
 'mismatch_24.json',
 'mismatch_25.json',
 'mismatch_26.json',
 'mismatch_27.json',
 'mismatch_28.json',
 'mismatch_29.json',
 'mismatch_3.json',
 'mismatch_30.json',
 'mismatch_31.json',
 'mismatch_32.json',
 'mismatch_33.json',
 'mismatch_34.json',
 'mismatch_35.json',
 'mismatch_36.json',
 'mismatch_37.json',
 'mismatch_38.json',
 'mismatch_39.json',
 'mismatch_4.json',
 'mismatch_40.json',
 'mismatch_41.json',
 'mismatch_42.json',
 'mismatch_43.json',
 'mismatch_44.json',
 'mismatch_45.json',
 'mismatch_46.json',
 'mismatch_47.json',
 'mismatch_48.json',
 'mismatch_49.json',
 'mismatch_5.json',
 'mismatch_50.json',
 'mismatch_51.json',
 'mismatch_52.json',
 'mismatch_53.json',
 'mismatch_54.json',
 'mismatch_55.json',
 'mismatch_56.json',
 'mismatch_57.json',
 'mismatch_58.json',
 'mismatch_59.json',
 'mismatch_6.json',
 'mismatch_60.json',
 'mismatch_61.json',
 'mismatch_62.json',
 'mismatch_63.json',
 'mismatch_64.json',
 'mismatch_65.json',
 'mismatch_66.json',
 'mismatch_67.json',
 'mismatch_68.json',
 'mismatch_69.json',
 'mismatch_7.json',
 'mismatch_70.json',
 'mismatch_71.json',
 'mismatch_72.json',
 'mismatch_73.json',
 'mismatch_74.json',
 'mismatch_75.json',
 'mismatch_76.json',
 'mismatch_77.json',
 'mismatch_78.json',
 'mismatch_79.json',
 'mismatch_8.json',
 'mismatch_80.json',
 'mismatch_81.json',
 'mismatch_82.json',
 'mismatch_83.json',
 'mismatch_84.json',
 'mismatch_85.json',
 'mismatch_86.json',
 'mismatch_87.json',
 'mismatch_88.json',
 'mismatch_89.json',
 'mismatch_9.json',
 'mismatch_90.json',
 'mismatch_91.json',
 'mismatch_92.json',
 'mismatch_93.json',
 'mismatch_94.json',
 'mismatch_95.json',
 'mismatch_96.json',
 'mismatch_97.json',
 'mismatch_98.json',
 'mismatch_99.json']

In [36]:

def fetch_json_data(data_to_load):
    df=pd.DataFrame()
    for d in data_to_load:
        with open(os.path.join("resume-score-details", d), "r") as file:
            data = json.load(file)

            row = {
                "job_description": data['input']['job_description'],
                "resume": data['input']['resume'],
                "macro_scores": data['output']['scores']['aggregated_scores']['macro_scores'],
                "micro_scores": data['output']['scores']['aggregated_scores']['micro_scores']
            }

            df = pd.concat([df, pd.DataFrame([row])], ignore_index=True)
    return df

In [37]:
df=fetch_json_data(data_to_load=data_to_load)
df.head()

,job_description,resume,macro_scores,micro_scores
0,## Job Title: Senior Electrical Engineering Pr...,"ABDULLAH JAWAID \nGulshan e Iqbal, block 2, Ka...",9.00,9.00
1,## Job Title: Senior Electrical Engineering Pr...,Team Lead \n Experience Required: 10 to 15 ...,7.00,6.00
2,## Job Title: Senior Electrical Project Manage...,Team Lead \n Experience Required: 10 to 15 ...,9.00,8.09
3,# Job Title: Electrical Engineer - Automation ...,MUHAMMAD NADEEM\nELECTRICAL ENGINEER\nPROFILE...,5.96,7.28
4,### Job Title: International Business Developm...,"Milat Road DHA 3, Lahore https://www.linkedin....",3.42,5.00

In [38]:
df.shape

(889, 4)

In [39]:
df.to_csv("final_data.csv",index=False,escapechar="\\")

In [40]:
import nltk
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
import re

STOPWORDS = set(list(ENGLISH_STOP_WORDS)) - {"not", "no", "nor"}

def preprocess_text(text):
    if not isinstance(text, str):
        return ""

    text = re.sub(r'http\S+|www\S+|https\S+', ' ', text)

    text = re.sub(r'\S+@\S+', ' ', text)

    text = re.sub(r'<[^>]+>', ' ', text)

    text = re.sub(r'\s+', ' ', text).strip()

    text = re.sub(r"(\'re)", " are", text)
    text = re.sub(r"(\'s)", " is", text)
    text = re.sub(r"(\'ve)", " have", text)
    text = re.sub(r"(n\'t)", " not", text)
    text = re.sub(r"(\'ll)", " will", text)
    text = re.sub(r"(\'d)", " would", text)
    text = re.sub(r"(\'m)", " am", text)

    text = text.lower()

    text = re.sub(r'[^a-z\s]', ' ', text)

    tokens = [tok for tok in text.split() if len(tok) > 2 and tok not in STOPWORDS]

    return " ".join(tokens)

In [41]:
df['resume']=df['resume'].apply(preprocess_text)
df['job_description']=df['job_description'].apply(preprocess_text)

In [42]:
df

,job_description,resume,macro_scores,micro_scores
0,job title senior electrical engineering projec...,abdullah jawaid gulshan iqbal block karachi su...,9.00,9.00
1,job title senior electrical engineering projec...,team lead experience required years relevant e...,7.00,6.00
2,job title senior electrical project manager co...,team lead experience required years relevant e...,9.00,8.09
3,job title electrical engineer automation contr...,muhammad nadeem electrical engineer profile mo...,5.96,7.28
4,job title international business development m...,milat road dha lahore scan data entry receivin...,3.42,5.00
...,...,...,...,...
884,digital marketing strategist innovatetech corp...,sohaib afzal lahore pakistan professional summ...,7.00,4.32
885,join apex global solutions business developmen...,hassan javed artificial intelligence developer...,5.00,5.10
886,business development manager join fictional co...,umerqayyum profile tofindachallengingjobinadyn...,3.30,2.22
887,join apex global solutions business developmen...,sharoon bakhshi phone email lums edu lahore pa...,4.87,4.45
888,business development manager join fictional co...,hamza tahir business expansion specialist moti...,7.71,5.39

In [43]:
def prepare_input(sample):
    resume = sample['resume']
    jd = sample['job_description']
    
    text = resume + " [SEP] " + jd
    
    macro = sample["macro_scores"]
    micro = sample["micro_scores"]
    
    return text, [macro, micro]

In [44]:
from transformers import AutoTokenizer

tokenizer=AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize(text):
    return tokenizer(
        text,
        padding="max_length",
        truncation=True,
        max_length=512,
        return_tensors="pt"
    )

c:\Users\vansh\Projects\ML-Learner\python_backend\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [48]:
tokenize("Hello world")

{'input_ids': tensor([[ 101, 7592, 2088,  102,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]])}

In [52]:
import torch
from torch.utils.data import DataLoader,Dataset

class ResumeDataset(Dataset):
    def __init__(self,data):
        self.sample=[prepare_input(x) for _,x in data.iterrows()]

    def __len__(self):
        return len(self.sample)


    def __getitem__(self, idx):    
        text,labels=self.sample[idx]

        enc=tokenize(text)

        return {
            "input_idx":enc['input_ids'].squeeze(0),
            "attention_mask":enc['attention_mask'].squeeze(0),
            "labels":torch.tensor(labels,dtype=torch.float)

        }

In [53]:
import torch.nn as nn
from transformers import AutoModel

class ResumeScore(nn.Module):
    def __init__(self, ):
        super().__init__()

        self.bert=AutoModel.from_pretrained("bert-base-uncased")

        self.regressor=nn.Sequential(
            nn.Linear(768,256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256,2) # macro ,micro

        )

    def forward(self,input_ids,attention_mask):
        outputs=self.bert(input_ids,attention_mask)

        cls_output=outputs.last_hidden_state[:,0] # cls token

        return self.regressor(cls_output)

In [ ]:
dataset=ResumeDataset(data=df)

dataset_loader=DataLoader(dataset=dataset,batch_size=8,shuffle=True)

model=ResumeScore()
optimizer=torch.optim.AdamW(model.parameters(),lr=2e-5)

loss_fn=nn.MSELoss()

In [ ]:
epochs=10
from tqdm import tqdm
for epoch in tqdm(range(epochs)):
    for batch in tqdm(loader):
        optimizer.zero_grad()
        output=model(batch["input_ids"], batch["attention_mask"])

        loss=loss_fn(output,batch['labels'])

        loss.backward()

        optimizer.step()

    print("Epoch done",loss.item())